window.CONV = [
{id:"christianity", name:"Christianity", short:"~2.4 billion", bar:29, color:"#3e5a48",
pop:"About 2.4 billion people. Largest named religion.",
what:"One God. Jesus of Nazareth is Messiah and Lord. The church is a people. Scripture is the Bible.",
quote:{t:"And the Word was made flesh, and dwelt among us, (and we beheld his glory…)", s:"John 1:14 · King James Bible"},
parts:[{n:"Catholic", w:48, c:"#7a4e2a", l:"~1.3B"},{n:"Protestant + Independent", w:38, c:"#3e5a48", l:"800M+"},{n:"Orthodox families", w:14, c:"#5c3d6e", l:"~220M"}],
end:"Christ has come. Christ will come again. The Judge is a person.",
qEnd:{t:"And then shall they see the Son of man coming in the clouds with great power and glory.", s:"Mark 13:26"},
power:"Technique that builds a name without worship is an old story.",
qPow:{t:"Go to, let us build us a city and a tower, whose top may reach unto heaven; and let us make us a name.", s:"Genesis 11:4"},
tech:"A system that disciples attention all day is already a church. A model is not the Word made flesh.",
twigs:[
{n:"Catholic — Latin", w:"Mass as the center of the Western church.", q:{t:"This is my body which is given for you: this do in remembrance of me.", s:"Luke 22:19"}},
{n:"Pentecostal / charismatic", w:"Largest Protestant energy worldwide.", q:{t:"Beloved, believe not every spirit, but try the spirits whether they are of God.", s:"1 John 4:1"}},
{n:"Evangelical / Baptist / nondenom.", w:"Conversion, Bible, mission.", q:{t:"Ye must be born again.", s:"John 3:7"}},
{n:"Eastern Orthodox", w:"Liturgy. Theosis.", q:{t:"The Word was made flesh, and dwelt among us.", s:"John 1:14"}},
{n:"Historically Black churches", w:"AME, COGIC, National Baptist.", q:{t:"I am the LORD thy God, which have brought thee out of the land of Egypt.", s:"Exodus 20:2"}}
]},
{id:"islam", name:"Islam", short:"~2.0 billion", bar:25, color:"#2f6b4f",
pop:"About 2.0 billion.",
what:"One God (tawhid). Muhammad is the final prophet. Shirk — giving a creature God’s place — is the core sin.",
quote:{t:"Say: He is Allah, the One and Only; Allah, the Eternal, Absolute; He begetteth not, nor is He begotten; and there is none like unto Him.", s:"Qur’an 112:1–4 · Yusuf Ali"},
parts:[{n:"Sunni", w:87, c:"#2f6b4f", l:"85–90%"},{n:"Shia", w:11, c:"#4a8a68", l:"10–13%"},{n:"Ibadi + other", w:2, c:"#8fb89f", l:"small"}],
end:"The Hour comes. Signs are watched. They are not scheduled by a laboratory.",
qEnd:{t:"When the sun is folded up; when the stars fall, losing their lustre; when the mountains vanish like a mirage…", s:"Qur’an 81:1–3 · Yusuf Ali"},
power:"Pharaoh is the type of a ruler who claims divinity.",
qPow:{t:"And Pharaoh said: O chiefs! I know not that ye have a god other than me.", s:"Qur’an 28:38 · Pickthall"},
tech:"A machine treated as knower-of-all sits near shirk.",
twigs:[
{n:"Hanafi (Sunni)", w:"Largest school. South Asia, Turkey, Central Asia, the Balkans."},
{n:"Shafi‘i (Sunni)", w:"Egypt, East Africa, Indonesia, Malaysia."},
{n:"Maliki (Sunni)", w:"North and West Africa."},
{n:"Hanbali / Salafi currents", w:"Smaller classical school; strong modern Gulf influence."},
{n:"Twelver Shia", w:"Iran, Iraq, Lebanon, Bahrain. The twelfth Imam in occultation."}
]},
{id:"unaffiliated", name:"Unaffiliated", short:"1.2–1.9B", bar:16, color:"#5a6570",
pop:"1.2–1.9 billion depending on how China is counted. Not one church.",
what:"Atheists, agnostics, nothing-in-particular, and people who keep rites without a label.",
quote:{t:"An agnostic is one who thinks the question of God’s existence is not settled.", s:"After T. H. Huxley, who coined ‘agnostic’ — not scripture"},
parts:[{n:"Nothing in particular / SBNR", w:50, c:"#8a93a0", l:"often largest slice"},{n:"Atheist", w:30, c:"#5a6570", l:"smaller than the bin"},{n:"Agnostic", w:20, c:"#c5cad0", l:"uncounted cleanly"}],
end:"No revealed finale is required.",
qEnd:{t:"The cosmos is all that is or ever was or ever will be.", s:"Carl Sagan, Cosmos — an essay some treat as last word"},
power:"The danger is human and institutional.",
qPow:{t:"Extraordinary claims require extraordinary evidence.", s:"A modern proverb, not a verse"},
tech:"Who holds the logs, the compute, and the law is the live question.",
twigs:[{n:"Quiet atheist", w:"Does not organize around unbelief."},{n:"Anti-theist", w:"Treats religion as a harm to reduce."},{n:"Marxist-materialist", w:"Official in some states; often beside folk practice."},{n:"Spiritual but not religious", w:"Experience without a creed."}]},
{id:"hindu", name:"Hindu families", short:"~1.2 billion", bar:15, color:"#c9853a",
pop:"About 1.2 billion, almost all on the Indian subcontinent.",
what:"Not a single church. Dharma, karma, rebirth, many schools.",
quote:{t:"Whenever there is a decline of dharma and a rise of adharma, I send forth myself.", s:"Bhagavad Gita 4.7"},
parts:[{n:"Vaishnava", w:45, c:"#c9853a", l:"largest bhakti family"},{n:"Shaiva", w:30, c:"#a66b28", l:"Shiva-centered"},{n:"Shakta + Smartism + other", w:25, c:"#e8c49a", l:"Goddess / five-deity"}],
end:"Ages rise and fall. Kali yuga is a darkening.",
qEnd:{t:"For the soul there is neither birth nor death… it is not slain when the body is slain.", s:"Bhagavad Gita 2.20"},
power:"Adharma is disorder when duty is forgotten.",
qPow:{t:"You have a right to the action alone, never to its fruits.", s:"Bhagavad Gita 2.47"},
tech:"A system that accelerates craving can be read as the weather of a darkening age.",
twigs:[{n:"Gaudiya Vaishnava", w:"Krishna-centered; includes ISKCON."},{n:"Sri Vaishnava", w:"South Indian temple lines."},{n:"Shaiva Siddhanta", w:"Tamil temple theology."}]},
{id:"buddhist", name:"Buddhist families", short:"~500 million", bar:6, color:"#7a9bb0",
pop:"About 500 million who take the name.",
what:"No creator-God required. Liberation is the end of craving and ignorance.",
quote:{t:"All conditioned things are impermanent. When one sees this with wisdom, one turns away from suffering.", s:"Dhammapada 277"},
parts:[{n:"Mahayana", w:55, c:"#7a9bb0", l:"East Asia"},{n:"Theravada", w:35, c:"#4d7388", l:"Sri Lanka + SE Asia"},{n:"Vajrayana", w:10, c:"#c5d6e0", l:"Tibet + Himalaya"}],
end:"Nirvana is unbinding.",
qEnd:{t:"Hatred is never appeased by hatred in this world. By non-hatred alone is hatred appeased.", s:"Dhammapada 5"},
power:"Attachment — including to views and to tools — is the engine of suffering.",
qPow:{t:"Mind precedes all things. If with a corrupt mind one speaks or acts, suffering follows.", s:"Dhammapada 1"},
tech:"An AI companion is a new object of clinging.",
twigs:[{n:"Pure Land", w:"Trust in Amitabha."},{n:"Chan / Zen", w:"Meditation lineages."},{n:"Thai / Burmese Theravada", w:"Largest living Pali-canon bodies."},{n:"Gelug", w:"Dalai Lama’s school."}]},
{id:"chinese", name:"Chinese landscape", short:"Not one number", bar:8, color:"#8a6a3a",
pop:"Folk-religionist tallies sit near 400 million. Practice is far wider.",
what:"Not one church. Confucian ethic + Daoist ritual + Chinese Buddhism on folk practice, beside official atheism.",
quote:{t:"The Master said, ‘Filial piety and fraternal respect — these are the root of humaneness.’", s:"Analects 1.2"},
parts:[{n:"Folk + ancestors", w:40, c:"#8a6a3a", l:"the mountain base"},{n:"Confucian ethic", w:25, c:"#c4a574", l:"often not called religion"},{n:"Chinese Buddhism", w:20, c:"#7a9bb0", l:"shared temples"},{n:"Daoist", w:15, c:"#5f7d68", l:"few registered"}],
end:"No single last-day courtroom is required. The dead remain in the family.",
qEnd:{t:"The Way that can be spoken of is not the constant Way. The name that can be named is not the constant name.", s:"Daodejing 1"},
power:"Disorder is a broken relationship — to parents, to place, to Heaven.",
qPow:{t:"Be respectful in the handling of affairs, be true, be economical, and love the people.", s:"Analects 1.5"},
tech:"A placeless model has no ancestor tablet and no village god.",
twigs:[{n:"Ancestor rite", w:"The dead stay in the house’s story."},{n:"Zhengyi Daoist", w:"Married priests; local ritual."},{n:"Lay Pure Land in China", w:"Most common Buddhist lay form."}]},
{id:"indigenous", name:"African & indigenous", short:"~300 million+", bar:5, color:"#6b5344",
pop:"Ethnoreligionist tallies sit near 300 million. Lived practice is larger.",
what:"Land, ancestors, spirits, balance. Not one scripture.",
quote:{t:"The dead are not under the earth. They are in the tree that rustles…", s:"Birago Diop, ‘Spirits’ — a taught African poem, not a closed canon"},
parts:[{n:"African traditional", w:70, c:"#6b5344", l:"often beside church/mosque"},{n:"Americas + Pacific", w:30, c:"#a89078", l:"many nations"}],
end:"What must not be broken is often local.",
qEnd:{t:"Treat the earth well. It was loaned to you by your children.", s:"Attributed proverb in several Native teaching collections — proverb, not one nation’s scripture"},
power:"Extraction that ignores place is the old injury.",
qPow:{t:"I am the land. The land is me.", s:"A common indigenous claim of relation — wording varies by nation"},
tech:"A model with no treaty and no grave cannot keep a promise it never made.",
twigs:[{n:"Yoruba-derived + diaspora", w:"Including lines mixed with Catholic saints in the Americas."},{n:"Native nations of North America", w:"Many nations, not one faith."}]},
{id:"jewish", name:"Judaism", short:"~15 million", bar:2, color:"#3d5a80",
pop:"About 15 million.",
what:"Covenant. One God. A people and a law.",
quote:{t:"Hear, O Israel: The LORD our God is one LORD.", s:"Deuteronomy 6:4 · Shema"},
parts:[{n:"Orthodox", w:20, c:"#3d5a80", l:"halakha binding"},{n:"Conservative / Reform / secular", w:80, c:"#7a9bb0", l:"peoplehood with sliding law"}],
end:"Repair of the world. Do not complete history on your own timetable.",
qEnd:{t:"They shall beat their swords into plowshares… nation shall not lift up sword against nation.", s:"Isaiah 2:4"},
power:"Idols include the state and the tool.",
qPow:{t:"Thou shalt have no other gods before me.", s:"Exodus 20:3"},
tech:"A model that claims to finish redemption is offering a false messiah in silicon.",
twigs:[{n:"Modern Orthodox", w:"Law with modern life."},{n:"Haredi", w:"Separation as fidelity."},{n:"Reform / secular Jewish", w:"Ethics and peoplehood."}]},
{id:"sikh", name:"Sikhism", short:"~25–30 million", bar:3, color:"#b35a1f",
pop:"About 25–30 million.",
what:"One God. The Guru Granth Sahib as living guru.",
quote:{t:"There is one God. His name is Truth. He is the Creator.", s:"Mul Mantar · opening of the Guru Granth Sahib"},
parts:[{n:"Khalsa / Sahajdhari spectrum", w:100, c:"#b35a1f", l:"same book; different discipline"}],
end:"The soul returns to God.",
qEnd:{t:"By the Name, the soul is dyed in the color of God.", s:"Naam teaching in the Granth — short study quotation"},
power:"The saint-soldier stands against tyranny.",
qPow:{t:"Recognize all humankind as one.", s:"Taught Sikh line from the tradition of Guru Gobind Singh"},
tech:"A voice without a congregation is not a guru.",
twigs:[{n:"Punjab and diaspora gurdwaras", w:"The ordinary living body."}]},
{id:"science", name:"Scientific naturalism", short:"A method", bar:4, color:"#1d1d1f",
pop:"Not a census religion.",
what:"The world is knowable by test. When this becomes a church, it has left the method.",
quote:{t:"A scientific statement is one that can be proven wrong in principle. If it cannot fail, it is not science.", s:"Falsifiability, after Karl Popper — method, not scripture"},
parts:[{n:"Method only", w:70, c:"#1d1d1f", l:"most working scientists"},{n:"Worldview naturalism", w:30, c:"#6e6e73", l:"nature is all there is"}],
end:"No official end.",
qEnd:{t:"We are a way for the cosmos to know itself.", s:"Sagan — an essay, not a finding about destiny"},
power:"Bad incentives, fraud, weapons — and treating ‘what we can measure’ as ‘what is real.’",
qPow:{t:"The first principle is that you must not fool yourself — and you are the easiest person to fool.", s:"Richard Feynman"},
tech:"AI is instruments plus data plus labor. It does not become a person by sounding like one.",
twigs:[{n:"Believing scientist", w:"Two books: nature and whatever they worship."},{n:"Physicalist", w:"Mind is what brains do."},{n:"Transhuman current", w:"A hope, not a finding."}]},
{id:"small", name:"Small currents", short:"Ideas, not billions", bar:2, color:"#4a3048",
pop:"Not in the billions.",
what:"Gnosticism is mostly an ancient library. Public Satanism is usually atheistic theater or a political project.",
quote:{t:"If you bring forth what is within you, what you have will save you.", s:"Gospel of Thomas 70 · Nag Hammadi"},
parts:[{n:"Historical Gnostic texts", w:34, c:"#4a3048", l:"ancient"},{n:"Public Satanism", w:33, c:"#1d1d1f", l:"tens of thousands"},{n:"New Age market", w:33, c:"#8a6a3a", l:"uncounted"}],
end:"Gnostic: escape a false world. LaVeyan: no world to escape.",
qEnd:{t:"This world is a corpse-eater.", s:"Gospel of Thomas 60 · historical text"},
power:"LaVeyan: the self is the unit.",
qPow:{t:"There is no God. Satan is a symbol of pride and liberty.", s:"Paraphrase of LaVeyan stance, 1969 — a pamphlet, not ancient scripture"},
tech:"A model that offers secret knowledge for the few rhymes with ancient gnosis. That does not make Gnosticism large.",
twigs:[{n:"Nag Hammadi study", w:"Read as history."},{n:"Church of Satan / LaVeyan", w:"Atheistic ritual as theater of the self."},{n:"The Satanic Temple", w:"Secular political project using the name."}]}
];
