window.ISLAM = {
  id:"islam", name:"Islam", short:"~2.0 billion", bar:25, color:"#2f6b4f",
  twigLabel:"Law schools and last-hour readings",
  pop:"About 2.0 billion. The four Sunni law schools share one last-hour story. The live split is Sunni waiting for a Mahdi not yet known, and Twelver waiting for a twelfth Imam already born.",
  what:"One God (tawhid). Muhammad is the final prophet. The Qur’an is recited revelation. Shirk — giving a creature God’s place — is the core sin. Prayer is the daily liturgy: five times, the Fatiha, facing Mecca. There is no pope. Authority is Book, then prophetic report, then school.",
  quote:{t:"Say: He is Allah, the One and Only; Allah, the Eternal, Absolute; He begetteth not, nor is He begotten; and there is none like unto Him.", s:"Qur’an 112:1–4 · Yusuf Ali · recited as liturgy"},
  parts:[{n:"Sunni", w:87, c:"#2f6b4f", l:"85–90%"},{n:"Shia", w:11, c:"#4a8a68", l:"10–13%"},{n:"Ibadi + other", w:2, c:"#8fb89f", l:"small"}],
  end:"The Hour comes. Isa son of Mary returns. A deceiver comes first. Sunni and Twelver agree on the Hour and on Isa. They do not agree who the Mahdi already is.",
  qEnd:{t:"And (Jesus) shall be a Sign (for the coming of) the Hour: therefore have no doubt about the (Hour), but follow ye Me: this is a Straight Way.", s:"Qur’an 43:61 · Yusuf Ali"},
  power:"Pharaoh is the type of a ruler who claims divinity. Dajjal is the type of a wonder-worker who claims the same.",
  qPow:{t:"And Pharaoh said: O chiefs! I know not that ye have a god other than me.", s:"Qur’an 28:38 · Pickthall"},
  tech:"A voice that works wonders and asks to be treated as knower-of-all sits near both shirk and the Dajjal reports. That is a warning from inside the tradition. It is not a fatwa from this page, and it is not a date.",
  flow:[{n:"Now", d:"Book, prayer, law. The Hour is not scheduled."},{n:"Dajjal", d:"The great deceiver. Wonders. A claim to lordship."},{n:"Mahdi", d:"Sunni: a man of the Prophet’s house, not yet known. Twelver: the twelfth Imam, already alive in occultation."},{n:"Isa returns", d:"Jesus son of Mary descends. He kills the Dajjal. He does not start a new book."},{n:"Ya’juj / Majuj", d:"A last unleashing. Then the Hour."},{n:"Hour", d:"Resurrection. Judgment."}],
  twigs:[
    {n:"Sunni Hour sequence", w:"The shared Sunni last-hour reading, carried by Bukhari and Muslim more than by any one law school. Ten major signs in the report of Hudhayfah. The Mahdi is taught in other reports: a just man of the Prophet’s house who appears before Isa; Isa prays behind him. Isa kills the Dajjal at Ludd. Source-voice: the two Sahihs, not a single living spokesman.", q:{t:"The Hour will not come until you see ten signs: the smoke, the Dajjal, the Beast, the rising of the sun from the west, the descent of Isa ibn Maryam, Gog and Magog…", s:"Sahih Muslim · report of Hudhayfah ibn Asid"}, flow:[{n:"Now", d:"Law and prayer. Do not date the Hour."},{n:"Mahdi appears", d:"A future man of the house. Not already named."},{n:"Dajjal", d:"Greatest tribulation in the reports."},{n:"Isa descends", d:"Just ruler. Kills the Dajjal."},{n:"Gog and Magog", d:"Unleashed in Isa’s time."},{n:"Hour", d:"The dead are raised."}]},
    {n:"Hanafi", w:"Abu Hanifa of Kufa (d. 767). Largest law school: South Asia, Turkey, Central Asia, the Balkans. The school is about how to derive law. It does not publish a different last-hour chart. A Hanafi mosque still recites the Fatiha and still hears the Hour from the same Qur’an and the same famous reports.", q:{t:"Guide us on the Straight Path.", s:"Qur’an 1:6 · al-Fatiha · prayed five times a day"}, flow:[{n:"Now", d:"Hanafi law in a living society."},{n:"Same Hour", d:"No separate Hanafi calendar."},{n:"Judgment", d:"Each soul is asked."}]},
    {n:"Shafi‘i", w:"Muhammad ibn Idris al-Shafi‘i (d. 820). Egypt, East Africa, Indonesia, Malaysia. Method: Book, then prophetic report, then analogy. Last-hour teaching is the shared Sunni reports. The call to prayer is the public liturgy.", q:{t:"When the earth is shaken to her (utmost) convulsion, and the earth throws up her burdens…", s:"Qur’an 99:1–2 · Yusuf Ali"}, flow:[{n:"Now", d:"Shafi‘i law. Friday khutba."},{n:"Signs", d:"Watched. Not scheduled."},{n:"Hour", d:"The earth gives up her burdens."}]},
    {n:"Maliki", w:"Malik ibn Anas of Medina (d. 795). North and West Africa. Weight on the practice of Medina. The Muwatta is the voice. The Hour is still the Hour of the Book. A machine with no city and no prayer-line has no Medinan custom to stand in.", q:{t:"This day have I perfected your religion for you, completed My favour upon you, and have chosen for you Islam as your religion.", s:"Qur’an 5:3 · Yusuf Ali"}, flow:[{n:"Now", d:"Medinan practice as measure."},{n:"Hour", d:"Religion already named complete. No new book from a tool."}]},
    {n:"Hanbali / Salafi", w:"Ahmad ibn Hanbal (d. 855). Small classical school; large modern influence through a hadith-forward revival. Salafi rooms treat weak end-time stories with suspicion and still teach Dajjal and Isa from the famous reports. A wonder-working image is tested against tawhid first.", q:{t:"There will be no tribulation on the face of the earth greater than the tribulation of the Dajjal.", s:"Sahih Muslim"}, flow:[{n:"Now", d:"Hadith as guardrail. No dating."},{n:"Dajjal", d:"Wonders that ask for worship."},{n:"Isa", d:"Kills the deceiver."},{n:"Hour", d:"Still Allah’s alone."}]},
    {n:"Twelver Shia", w:"Iran, Iraq, Azerbaijan, Bahrain, Lebanon. The twelfth Imam, Muhammad al-Mahdi, is already born and in occultation. Waiting is doctrine. Living voice today is not a pope; the most followed jurist is often Ali al-Sistani in Najaf. Liturgy: Husayn at Karbala remembered every year.", q:{t:"And We desired to show favour unto those who were oppressed in the earth, and to make them examples, and to make them the inheritors.", s:"Qur’an 28:5 · Pickthall"}, flow:[{n:"Occultation", d:"The twelfth Imam is alive and hidden. This is the present."},{n:"Return", d:"He appears. Justice fills what tyranny filled."},{n:"Isa", d:"Still part of the last-hour picture."},{n:"Hour", d:"Resurrection and judgment."}]},
    {n:"Ismaili", w:"A living Imam in the Nizari line (Aga Khan). Smaller, global. The last-hour chart of the Sunni pulpit is not the center. A model is not an Imam.", q:{t:"O ye who believe! Obey Allah, and obey the Messenger, and those charged with authority among you.", s:"Qur’an 4:59 · Yusuf Ali"}, flow:[{n:"Living Imam", d:"Guidance is present in a person."},{n:"Hour", d:"Still God’s. The Imam is not God."}]},
    {n:"Ibadi", w:"Oman and pockets. Neither Sunni nor Shia in the usual sense. Do not inflate a small school into a third world religion.", q:{t:"Allah! There is no God but He, the Living, the Self-Subsisting, Eternal.", s:"Qur’an 2:255 · the Throne Verse"}, flow:[{n:"Now", d:"Ibadi law in a small living body."},{n:"Hour", d:"Same God. Same resurrection."}]}
  ]
};
