window.NEWS_ASOF = "2026-09-14";
window.TRACK = [
  {id:"aug20", date:"2026-08-20", title:"Some Catholics refuse AI chatbots",
    what:"A National Catholic Register story: a growing group of Catholics will not use chatbots. They say Pope Leo’s encyclical Magnifica humanitas (May 2026) tells them to be that cautious. The Pope has not banned chatbots. He has said they can be useful if watched, and that priests should not let a program write the Sunday sermon.",
    href:"https://www.ncregister.com/news/the-catholic-anti-ai-movement-is-here",
    read:{christianity:{g1:"This is an argument inside the church about whether to use a new tool. It is not Jesus coming back. Christians already believe Jesus died, rose from the dead, and will return as Judge. A news story about chatbots does not change that.", g2:{"Catholic":"Rome wrote a letter on AI. It did not ban the tools. Some Catholics are stricter than the letter. That is allowed. It is not a new doctrine.","Protestant + Independent":"No pope letter binds a Baptist church or a PCA session. A Protestant pastor still has to decide: is this tool a study aid, or is it doing the preaching?","Orthodox families":"Orthodox worship is a room, bread, wine, and a face on an icon. A chatbot is none of those."}, g3:{"Latin Catholic":"The official line is watchfulness, not a ban. The refusal group is stricter than the Vatican.","PCA":"The PCA does not take orders from an encyclical. The sermon comes from Scripture, prayer, and a called preacher — not from a program.","Nondenominational / seeker":"These rooms already use a lot of production. A writing tool will slip in unless someone draws a line.","Pentecostal / AoG":"The question here is older than AI: is this voice from God? A fluent paragraph is not an answer to that."}}, islam:{g1:"Muslims do not take their last-day calendar from a papal letter. A chatbot is a tool. It is not the Hour."}, hindu:{g1:"This story is Catholic. A program that recites a verse is still not a guru with a living teacher-line."}}},
  {id:"aug27", date:"2026-08-27", title:"A Catholic chatbot finds millions of users",
    what:"The Economist reported that Magisterium AI — a chatbot trained on Catholic documents — now claims millions of users, in the same weeks the Vatican is writing rules for AI.",
    href:"https://www.economist.com/international/2026/08/27/ai-is-changing-religion-and-religions-are-trying-to-change-ai",
    read:{christianity:{g1:"A searchable library of church documents can help a student. It cannot baptize, marry, bury, or return as Christ. Do not confuse a helpful index with the living church.", g2:{"Catholic":"If the bot only points at what bishops already wrote, it is a library. If people start treating it as the bishop, it has left its lane.","Protestant + Independent":"Protestants will build their own versions. Same test: servant of the text, or replacement pulpit.","Orthodox families":"A bot that talks like a priest is still not the liturgy."}, g3:{"Latin Catholic":"Useful as a catalog. Not the teaching office of the church.","PCA":"A study aid is fine. A study aid that writes the sermon is not how grace ordinarily comes.","Nondenominational / seeker":"If the talk already sounds produced, a bot will be hard to hear as different from the room."}}, islam:{g1:"A Catholic document-bot is a product. It is not a sign of the Hour."}, hindu:{g1:"A verse-reciting program is not a living teacher-line."}}},
  {id:"aug28", date:"2026-08-28", title:"Pope Leo: do not let machines decide about human life",
    what:"Pope Leo XIV warned that decisions about human life should not be handed to machines. He asked for an ethical framework so technology serves life, peace, and the common good.",
    href:"https://www.ncregister.com/topic/ai",
    read:{christianity:{g1:"This is a moral warning: do not let software decide who lives. Christians can agree with that sentence without turning it into a countdown to the end of the world.", g2:{"Catholic":"This is the Pope naming a limit. It is social teaching, not a secret last-days calendar.","Protestant + Independent":"Many Protestants will say the same thing from the command not to murder. You do not need Rome to say it.","Orthodox families":"Life is a gift. A machine has no one to answer for a death."}, g3:{"PCA":"The confession already forbids taking innocent life. A new tool does not create a new commandment.","Mainline":"This lands as medicine, labor, and war policy.","Adventist":"Some will hear the speaking image in Revelation 13. That rhyme is in their preaching. It still does not date the Advent."}}, islam:{g1:"Islam already forbids unjust killing. A pope repeating a life-rule does not start the Hour."}, hindu:{g1:"This headline is Rome’s wording of a limit many families already have about harm."}}},
  {id:"sep06", date:"2026-09-06", title:"Bali meeting: AI should free people, not own them",
    what:"In Bali, a Vatican office and an education network closed a three-day meeting with leaders from 35 countries. Their line: stop asking only what AI can do; ask what human beings want to do with it. They set that next to Leo’s encyclical and a Balinese idea — Tri Hita Karana — harmony among people, place, and the divine.",
    href:"https://www.vaticannews.va/en/church/news/2026-09/scholas-chairs-congress-ai-must-liberare-not-enslave.html",
    read:{christianity:{g1:"Religious leaders asked a decent question: who is the tool for? That meeting is not the second coming. It is ethics talk across rooms that do not share a creed.", g2:{"Catholic":"The Vatican is taking the encyclical on the road and talking with other religions. That is diplomacy. It is not new Scripture.","Protestant + Independent":"Protestants were not the hosts. The question still reaches them: is this tool serving people, or are people serving the tool?","Orthodox families":"A conference is still not the liturgy."}, g3:{"Latin Catholic":"They are applying a letter already written.","PCA":"A good limit — tools should serve people — does not become a sacrament.","Nondenominational / seeker":"What do we want to do with it? is the live question in a produced room."}}, islam:{g1:"The meeting named a papal letter and a Balinese idea. It did not move the signs of the Hour. Do not date anything from a press release.", hindu:{g1:"Tri Hita Karana is a Balinese frame: people, place, the divine. Using it at an AI meeting does not make a chatbot a guru."}}}
];
window.trackReading = function(on,g2,g3,g4,ev){
  if(!on||!ev||!ev.read) return "";
  var pack=ev.read[on.id];
  if(!pack) return "<div class=\"gbox\"><em>This worldview</em>No written reading for this family on this story yet. That is better than inventing one.</div>";
  var h="<div class=\"gbox\"><em>Grain 1 · "+on.name+"</em>"+pack.g1+"</div>";
  if(g2&&pack.g2&&pack.g2[g2]) h+="<div class=\"gbox\"><em>Grain 2 · "+g2+"</em>"+pack.g2[g2]+"</div>";
  else if(!g2&&on.id==="christianity") h+="<div class=\"gbox\"><em>Next</em>Tap Catholic, Protestant, or Orthodox above to hear this same story from that body.</div>";
  if(g3&&pack.g3&&pack.g3[g3.n]) h+="<div class=\"gbox\"><em>Grain 3 · "+g3.n+"</em>"+pack.g3[g3.n]+"</div>";
  if(g4&&pack.g4&&pack.g4[g4.n]) h+="<div class=\"gbox\"><em>Grain 4 · "+g4.n+"</em>"+pack.g4[g4.n]+"</div>";
  return h;
};
window.fetchNewsHeadlines = async function(){
  var q="https://api.rss2json.com/v1/api.json?rss_url="+encodeURIComponent("https://news.google.com/rss/search?q=Pope+Leo+AI+OR+religion+artificial+intelligence&hl=en-US&gl=US&ceid=US:en");
  try{ var r=await fetch(q); var j=await r.json(); return (j.items||[]).slice(0,3).map(function(it){ return {title:it.title, href:it.link}; }); }
  catch(e){ return []; }
};
