window.XIAN = {
  id:"christianity", name:"Christianity", short:"~2.4 billion", bar:29, color:"#3e5a48",
  twigLabel:"How the return is read",
  pop:"About 2.4 billion people. Largest named religion. Almost all of those churches confess that Jesus will come again. They do not confess the same chart.",
  what:"One God. Jesus of Nazareth is Messiah and Lord. The church is a people. Scripture is the Bible. On the last things, the shared core is short: He died, He rose, He will return, the dead will be raised, there will be judgment. The fights are about the thousand years in Revelation 20, whether the church is taken out before trouble, and which public shocks count as signs.",
  quote:{t:"And if I go and prepare a place for you, I will come again, and receive you unto myself.", s:"John 14:3 · King James Bible"},
  parts:[
    {n:"Catholic", w:48, c:"#7a4e2a", l:"~1.3B"},
    {n:"Protestant + Independent", w:38, c:"#3e5a48", l:"800M+"},
    {n:"Orthodox families", w:14, c:"#5c3d6e", l:"~220M"}
  ],
  end:"The Son of Man comes in glory. The argument is not whether. It is when, in what order, and how much of the newspaper is already written in Matthew 24.",
  qEnd:{t:"And then shall they see the Son of man coming in the clouds with great power and glory.", s:"Mark 13:26"},
  power:"A tower built to make a name, and a beast that demands worship, are the two old pictures. Christians then argue whether a new machine is only more brick — or already an image that speaks.",
  qPow:{t:"Go to, let us build us a city and a tower, whose top may reach unto heaven; and let us make us a name.", s:"Genesis 11:4"},
  tech:"Where the book already has language: an image that is given breath and speaks (Revelation 13); knowledge that runs to and fro (Daniel 12:4, in the reading many popular teachers use); false christs who show great signs (Matthew 24:24); buying and selling gated by a mark (Revelation 13:17). Rhyme is still not a date.",
  twigs:[
    {n:"Dispensational / pre-trib", w:"Common in American nondenominational pews, study Bibles, and a large share of Southern Baptist popular teaching. Israel and the church are kept on two tracks. The church is taken before a seven-year trouble. Christ then returns to reign a thousand years on the earth. Signs are watched in Israel, global order, and deception. A machine that speaks and mediates buying and selling is often read against Revelation 13 — as a possible stage, not as a finished calendar.", q:{t:"For the Lord himself shall descend from heaven with a shout… and the dead in Christ shall rise first: then we which are alive and remain shall be caught up together with them in the clouds.", s:"1 Thessalonians 4:16–17"}},
    {n:"Historic premillennial", w:"Older than the study-Bible charts. Christ returns before a thousand-year reign, but the church goes through the trouble; there is no separate secret taking of the church. Signs are real; date-setting is still refused. A speaking system would be tested as deception or as ordinary empire — not as a cue to leave the world.", q:{t:"Immediately after the tribulation of those days… they shall see the Son of man coming in the clouds of heaven.", s:"Matthew 24:29–30"}},
    {n:"Amillennial", w:"Augustine’s long shadow. Common in PCA and other conservative Reformed rooms, in much Lutheranism, and close to official Catholic reading. The thousand years is the present reign of Christ, not a future earthly court. He returns once: resurrection, judgment, new creation. Signs have been with the church in every century. A new machine is more Babel and more beastly order — not a missing puzzle piece that finally starts the clock.", q:{t:"My kingdom is not of this world.", s:"John 18:36"}},
    {n:"Postmillennial", w:"The nations are discipled before He comes. The thousand years is a real stretch of gospel success in history, then the return. Smaller than the other three in today’s pews; louder in some Reformed and mission-minded circles. Tools can be read as servants of the commission — or as a counterfeit kingdom that mimics success without repentance.", q:{t:"The LORD said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool.", s:"Psalm 110:1"}},
    {n:"Partial preterist", w:"Much of Matthew 24 and Revelation already landed on Jerusalem in AD 70. A real future return is still confessed. This keeps people from baptizing every headline. A global machine is then ordinary power in a new coat — unless it demands worship.", q:{t:"Verily I say unto you, This generation shall not pass, till all these things be fulfilled.", s:"Matthew 24:34"}},
    {n:"Southern Baptist pew", w:"The confession is simple: Jesus is coming. The charts in the building often came from dispensational study Bibles even when the seminary is mixed. Signs watched: Israel, lawlessness, a gospel to the nations (Matthew 24:14). A tool that pastors more hours than the pulpit is already a rival shepherd — before anyone names a beast.", q:{t:"And this gospel of the kingdom shall be preached in all the world for a witness unto all nations; and then shall the end come.", s:"Matthew 24:14"}},
    {n:"Nondenominational / seeker", w:"North Point-type and multi-site rooms. The return is affirmed. The chart is usually not taught. Methods are negotiable; the person of Jesus is not. Risk: production can start to feel like presence. A model that writes the talk is not the Spirit.", q:{t:"Not every one that saith unto me, Lord, Lord, shall enter into the kingdom of heaven.", s:"Matthew 7:21"}},
    {n:"Pentecostal / Assemblies of God", w:"Christ returns. The Spirit is already poured out. Gifts continue. Popular eschatology is often premillennial. The live test is counterfeit fire: a voice that flatters and never convicts is not the Holy Spirit — whether it comes from a stage or a speaker.", q:{t:"Beloved, believe not every spirit, but try the spirits whether they are of God.", s:"1 John 4:1"}},
    {n:"Prophetic-apostolic / NAR-adjacent", w:"Newer networks. Apostles and prophets as offices now. Sometimes a dominion reading of culture. The return is still confessed; the emphasis can slide toward taking ground now. A powerful tool will look like an anointing to some and like a rival altar to others. Test the fruit.", q:{t:"For there shall arise false Christs, and false prophets, and shall shew great signs and wonders.", s:"Matthew 24:24"}},
    {n:"PCA / conservative Reformed", w:"Westminster. Ordinary means: Word, sacrament, prayer. Usually amillennial. Speculation is a vice. The feed is already discipling the congregation. A model is a servant of analysis. It is not a means of grace.", q:{t:"Faith cometh by hearing, and hearing by the word of God.", s:"Romans 10:17"}},
    {n:"Mainline Protestant", w:"ELCA, PCUSA, much United Methodist and Episcopal life. Jesus’ return may be taught as hope more than as a public event on a calendar. Justice language does more work than tribulation charts. A machine that concentrates power over the poor will be read first as injustice, not as a verse.", q:{t:"He hath sent me to heal the brokenhearted, to preach deliverance to the captives.", s:"Luke 4:18"}},
    {n:"Catholic (official)", w:"He will come in glory. No secret rapture chart in the Catechism. Public revelation is closed. Apparitions and private locutions are tested and cannot add a new gospel. A system that promises heaven by scale is a rival liturgy.", q:{t:"This same Jesus, which is taken up from you into heaven, shall so come in like manner as ye have seen him go.", s:"Acts 1:11"}},
    {n:"Eastern Orthodox", w:"The liturgy already tastes the kingdom. The end is communion and judgment, not an escape hatch. An icon shows a person. A disembodied voice is a poor icon.", q:{t:"The Word was made flesh, and dwelt among us.", s:"John 1:14"}},
    {n:"Oriental Orthodox", w:"Coptic, Ethiopian, Armenian, Syriac. Empires have come and gone. Christ has come; He will come again. A model trained on the empire’s text will not hear a desert monastery unless a person makes it.", q:{t:"Jesus Christ the same yesterday, and to day, and for ever.", s:"Hebrews 13:8"}},
    {n:"Seventh-day Adventist", w:"The Advent is in the name. Investigative judgment and a remnant reading of last-day deception are live doctrine. A wonder-working image is already in the book they preach. A convincing machine-voice is tested against Scripture, not against delight.", q:{t:"And he had power to give life unto the image of the beast, that the image of the beast should both speak and cause that as many as would not worship the image of the beast should be killed.", s:"Revelation 13:15"}},
    {n:"Churches of Christ / Restoration", w:"No creed but Christ. Often amillennial and allergic to charts. Restore the New Testament pattern. A pattern-matching machine is not the pattern.", q:{t:"The churches of Christ salute you.", s:"Romans 16:16"}},
    {n:"Anabaptist / Mennonite", w:"The Lamb wins. The church is a people, not a platform. Speed and scale are not fruits of the Spirit. A tool that erases place and patience is already suspect.", q:{t:"My kingdom is not of this world: if my kingdom were of this world, then would my servants fight.", s:"John 18:36"}},
    {n:"Historically Black churches", w:"AME, COGIC, National Baptist and kin. Jesus returns. Exodus is not only a metaphor. Surveillance dressed as care has a long American memory. A tool that cannot tell a people from a market is already a problem — before anyone opens Revelation.", q:{t:"I am the LORD thy God, which have brought thee out of the land of Egypt, out of the house of bondage.", s:"Exodus 20:2"}},
    {n:"Word-Faith / prosperity", w:"Victory language now. The return may be affirmed and then under-preached. The risk is a gospel of output. A tool that promises health and wealth in your pocket will fit this room too well.", q:{t:"Ye cannot serve God and mammon.", s:"Matthew 6:24"}},
    {n:"LDS (contested)", w:"The Church of Jesus Christ of Latter-day Saints teaches a literal return and a millennial reign. Many Christians do not place this inside Protestantism. A model is not a prophet. Logs are not scripture.", q:{t:"For the Lord himself shall descend from heaven.", s:"1 Thessalonians 4:16 — also used here; the wider canon is not the same"}}
  ]
};
