/* Local QA. Requires Playwright and axe-core; does not publish or contact external sites. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),output=process.env.ASTRA_QA_OUTPUT||'/tmp/astra-public-qa';fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404);res.end('Missing');return}const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.m4a':'audio/mp4'};res.setHeader('Content-Type',types[path.extname(p)]||'text/plain');res.end(fs.readFileSync(p))});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const b=await chromium.launch({executablePath:process.env.ASTRA_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});const ctx=await b.newContext();await ctx.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());const p=await ctx.newPage();const errors=[],missing=[],overflow=[],axe=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)missing.push(r.url())});
const routes=['/','/portfolio/','/seersolutions/','/seersolutions/s33r/','/seersolutions/s33r/method.html','/seersolutions/s33r/scenario.html','/convergence/','/lenses/','/grounded/','/adventure/','/anti-attachment/','/chronicle/','/rewind/','/open-fruit/','/faded-dependence/'];
for(const width of [320,375,390,430,768,1440]){await p.setViewportSize({width,height:900});for(const route of routes){await p.goto(base+route,{waitUntil:'domcontentloaded'});await p.waitForTimeout(80);const leak=await p.evaluate(()=>({body:document.documentElement.scrollWidth,view:innerWidth,offenders:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2&&getComputedStyle(e).position!=='absolute').slice(0,5).map(e=>e.className)}));if(leak.body>width+2)overflow.push({width,route,...leak});if([390,1440].includes(width)&&['/','/seersolutions/s33r/','/rewind/','/seersolutions/','/grounded/','/lenses/','/convergence/'].includes(route)){await p.screenshot({path:path.join(output,(route==='/'?'home':route.replaceAll('/','_'))+'-'+width+'.png'),fullPage:true})}if(width===1440&&process.env.ASTRA_AXE){await p.addScriptTag({path:process.env.ASTRA_AXE});const a=await p.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary})).slice(0,8)}))});if(a.length)axe.push({route,violations:a})}}}
fs.writeFileSync(path.join(output,'render-report.json'),JSON.stringify({errors,missing,overflow,axe},null,2));
// Navigation: small screen, Escape, search result, explicit focus return.
await p.setViewportSize({width:390,height:844});await p.goto(base);await p.locator('.seer-menu').click();assert.equal(await p.locator('.seer-menu').getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await p.locator('.seer-menu').getAttribute('aria-expanded'),'false');assert.equal(await p.evaluate(()=>document.activeElement.className),'seer-menu');await p.locator('.seer-menu').click();await p.locator('.search-open').click();await p.locator('#site-search').fill('music');await p.locator('.search-result').first().waitFor({state:'visible'});assert(await p.locator('.search-result').count()>0);await p.keyboard.press('Escape');
// Research scope and history branches, and static disclosure.
await p.goto(base+'/seersolutions/s33r/');await p.locator('[data-boundary="work"]').click();assert.match(await p.locator('#boundary-title').textContent(),/Withhold/);await p.locator('[data-boundary="correction"]').click();assert.match(await p.locator('#boundary-copy').textContent(),/superseded/);await p.locator('.evidence-row summary').first().click();assert(await p.locator('.evidence-content').first().isVisible());
await p.goto(base+'/rewind/#decision');assert.equal(await p.locator('[data-chapter]').count(),3);await p.locator('#decision summary').click();assert(await p.locator('#decision dd').first().isVisible());
// Existing synthetic release gate remains consequential.
await p.goto(base+'/seersolutions/');await p.locator('#missing').check();assert(await p.locator('#prepare').isDisabled());await p.locator('#missing').uncheck();await p.locator('[data-scenario="quality"]').click();assert.equal(await p.locator('#total').textContent(),'18');await p.locator('#prepare').click();assert.match(await p.locator('#review-summary').textContent(),/SYNTHETIC/);
// Complete tab semantics and deep links.
await p.goto(base+'/convergence/');await p.locator('[data-mode="atlas"]').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('[data-mode="eschatology"]').getAttribute('aria-selected'),'true');await p.locator('[data-mode="live"]').click();assert.match(await p.locator('#news-meta').textContent(),/not a live feed/);assert(await p.locator('#news-stage').isVisible());
// Lenses: mobile readable comparison, view keyboard, local note persistence.
await p.goto(base+'/lenses/');await p.locator('[data-view="compare"][aria-selected="true"]').waitFor();await p.locator('[data-view="compare"]').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('[data-view="matrix"]').getAttribute('aria-selected'),'true');await p.locator('#note-evidence').fill('Check the original source.');await p.locator('#save-note').click();await p.reload();assert.equal(await p.locator('#note-evidence').inputValue(),'Check the original source.');
// Portfolio music never starts on an unrelated gesture.
await p.goto(base+'/portfolio/');await p.locator('h1').click();assert(await p.evaluate(()=>[...document.querySelectorAll('audio')].every(a=>a.paused)));
// Chronicle filtering and deep link.
await p.goto(base+'/chronicle/');await p.locator('#journal-search').fill('boundary');assert(await p.locator('.decision-entry:visible').count()>0);await p.locator('#journal-search').fill('zzzznever');assert(await p.locator('#journal-empty').isVisible());
// Reduced motion and no-JS core routes.
await p.emulateMedia({reducedMotion:'reduce'});await p.goto(base);assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');
const nojs=await b.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});await nojs.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());const q=await nojs.newPage();for(const route of ['/','/rewind/','/seersolutions/s33r/','/chronicle/','/portfolio/']){await q.goto(base+route);assert(await q.locator('h1').isVisible());assert(await q.locator('main a').count()>0)}
const report={routes:routes.length,viewportWidths:[320,375,390,430,768,1440],renderChecks:90,errors,missing,overflow,axe,interactions:'passed',reducedMotion:'passed',noJavaScript:'core routes passed',externalRequests:'blocked intentionally; embeds require online human check'};fs.writeFileSync(path.join(output,'browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await b.close();server.close();if(errors.length||missing.length||overflow.length||axe.length)process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exit(1)});
